### ISSUE TITLE
Can’t load retinaface_r50_v1 model

### ISSUE THREAD

**Issue by addiajsjjs** [michaeltrs/RethinkNIRVIS#1]

**Comment by SilverRAN** [comment]
Hello! I’ve encountered the same issue as well. May I ask if you resolved it?

**Comment by addiajsjjs** [comment]
I remember that the model was only used for face cropping and aligning. So I replaced it with a similar alternative (like RetinaFace: https://github.com/serengil/retinaface) as a substitute, and it worked quite well.




Since the modified code was on my previous server and I’ve already left, I’m unfortunately unable to provide the updated version. However, if I remember correctly, I only changed a few lines of code to load a different model.




Hope you can solve it!




谢松言
***@***.***



        



         原始邮件
         
       
发件人：Weihang Ran ***@***.***&gt;
发件时间：2026年2月14日 00:05
收件人：michaeltrs/RethinkNIRVIS ***@***.***&gt;
抄送：qidian ***@***.***&gt;, State change ***@***.***&gt;
主题：Re: [michaeltrs/RethinkNIRVIS] Can’t load retinaface_r50_v1 model (Issue #1)



SilverRAN left a comment (michaeltrs/RethinkNIRVIS#1)

Hello! I’ve encountered the same issue as well. May I ask if you resolved it?

**Comment by SilverRAN** [comment]
It's very helpful! Thanks a lot!
